import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const seriouslyNostalgicFont = localFont({
  src: "./fonts/SeriouslyNostalgic-SemiCond.otf",
  variable: "--font-serif",
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Detour Dynamics",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${seriouslyNostalgicFont.variable} ${geistSans.variable} font-sans text-sand-12 bg-sand-1 dark antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
